apiVersion: apps/v1
kind: Deployment            # lets you change and handle more than a pod. so use deployments and not pods.
metadata:
  name: client-deployment
spec:
  replicas: 3               # specifies the number of pods this deployment is creating
  selector:                 # after the pods are created with metadata label down below needs to be found after creating. This does it.
    matchLabels:
      component: web
  template:                 # pod template. every single pod created by this deployment uses this
    metadata:
      labels:
        component: web
    spec:
      containers:
        - name: client
          image: stephengrider/multi-client
          ports:
            - containerPort: 3000